#!/bin/sh

TMP=/tmp
BUILDDIR=qucsbld

cd $TMP
mkdir -p $BUILDDIR
cd $BUILDDIR

git clone -b qucs-s-stable https://github.com/ra3xdh/qucs


cd qucs
rm -rf .git
rm -rf qucs-core

VERSION=`cat VERSION`
#VERSION=0.0.19
EXTRAVERSION=S
TARBALL=qucs-${VERSION}${EXTRAVERSION}.tar.gz

mv qucs qucs-${VERSION}${EXTRAVERSION}

cd qucs-${VERSION}${EXTRAVERSION}

sed -i -e '1 i\SET\(WITH_SPICE ON\)' CMakeLists.txt
sed -i -e '1 i\SET\(CMAKE_BUILD_TYPE Release\)' CMakeLists.txt


rm -rf qucs-attenuator
rm -rf qucs-rescodes
rm -rf qucs-transcalc
rm -rf qucs-edit
rm -rf qucs-filter-v2
#rm -rf examples
rm -rf qucs-help
#mv ../examples .

#sed -i -e 's/\"\.\.\/examples\"/\"examples\"/g' CMakeLists.txt

cd ..
tar cvfz $TARBALL qucs-${VERSION}${EXTRAVERSION}

rm $TMP/$TARBALL
mv $TARBALL $TMP
echo "Qucs tarball is: $TMP/$TARBALL"

cd $TMP
rm -rf $BUILDDIR

